component_depth: 1
languages:
- javascript

- name: javascript
  production:
    include:
      - .*/config/.*\.js
      - .*/controllers/.*\.js
      - .*/middleware/.*\.js
      - .*/models/.*\.js
      - .*/routes/.*\.js
      - .*/services/.*\.js
      - /app.js
  test:
    include:
#      - .*/test/.*\.js