language: node_js

node_js:
  - "iojs"
  - "8"

before_script:
  - npm install -g nodemon codecov

install:
  - npm install

script:
  - nodemon
  - codecov

env:
  - PORT=3000
  - URL=http://localhost:3000
  - DB_HOST=localhost
  - DB_USER=root
  - DB_PASS=
  - JWT_KEY=